In [6]:
import pandas as pd

# 1. Caminho real do seu arquivo CSV
caminho_arquivo = 'C:/Users/mdiir/Documents/code_unisales/Database_Tunning/AdventureWorks-for-Postgres-master/SalesOrderDetail.csv'

# 2. Lendo o arquivo com o separador correto (tabulação: sep='\t')
df_real = pd.read_csv(caminho_arquivo, sep='\t')

print("=== COLUNAS EXISTENTES NO SEU ARQUIVO CSV ===")
print(df_real.columns.tolist())

print("\n=== AMOSTRA DOS DADOS REAIS (HEAD) ===")
display(df_real.head())

=== COLUNAS EXISTENTES NO SEU ARQUIVO CSV ===
['43659', '1', '4911-403C-98', '1.1', '776', '1.2', '2024.9940', '.0000', '2024.994000', 'B207C96D-D9E6-402B-8470-2CC176C42283', '2022-05-30 00:00:00.000']

=== AMOSTRA DOS DADOS REAIS (HEAD) ===

,43659,1,4911-403C-98,1.1,776,1.2,2024.9940,.0000,2024.994000,B207C96D-D9E6-402B-8470-2CC176C42283,2022-05-30 00:00:00.000
0,43659,2,4911-403C-98,3,777,1,2024.994,0.0,6074.982,7ABB600D-1E77-41BE-9FE5-B9142CFC08FA,2022-05-30 00:00:00.000
1,43659,3,4911-403C-98,1,778,1,2024.994,0.0,2024.994,475CF8C6-49F6-486E-B0AD-AFC6A50CDD2F,2022-05-30 00:00:00.000
2,43659,4,4911-403C-98,1,771,1,2039.994,0.0,2039.994,04C4DE91-5815-45D6-8670-F462719FBCE3,2022-05-30 00:00:00.000
3,43659,5,4911-403C-98,1,772,1,2039.994,0.0,2039.994,5A74C7D2-E641-438E-A7AC-37BF23280301,2022-05-30 00:00:00.000
4,43659,6,4911-403C-98,2,773,1,2039.994,0.0,4079.988,CE472532-A4C0-45BA-816E-EEFD3FD848B3,2022-05-30 00:00:00.000

In [4]:
import pandas as pd
import dash
from dash import dcc, html, Input, Output
import plotly.express as px

caminho_arquivo = 'C:/Users/mdiir/Documents/code_unisales/Database_Tunning/AdventureWorks-for-Postgres-master/SalesOrderDetail.csv'

try:
    df_real = pd.read_csv(caminho_arquivo, sep=',')
    print(f"=== [ETL] 1. EXTRAÇÃO REAL CONCLUÍDA: {len(df_real)} registros carregados ===")
except FileNotFoundError:
    print(f"[ERRO] Arquivo não encontrado no caminho: {caminho_arquivo}")
    df_real = pd.DataFrame()

if not df_real.empty:
    
    df_transformado = df_real.drop_duplicates().copy()

    df_transformado['OrderQty'] = df_transformado['OrderQty'].fillna(0)
    df_transformado['UnitPrice'] = df_transformado['UnitPrice'].fillna(0.0)

    df_transformado['LineTotal_Calculated'] = df_transformado['OrderQty'] * df_transformado['UnitPrice']
    
    print(f"=== [ETL] 2. TRANSFORMAÇÃO CONCLUÍDA: {len(df_transformado)} registros válidos após limpeza ===")

    app = dash.Dash(__name__)

    app.layout = html.Div(style={'fontFamily': 'Arial, sans-serif', 'padding': '20px'}, children=[
        html.H2("Dashboard Analítico - AdventureWorks (Pipeline ETL Real)", style={'color': '#2C3E50'}),
        html.P("Projeto de Desenvolvimento de Dashboard Analítico | Jupyter + Plotly/Dash", style={'color': '#7F8C8D'}),
        
        dcc.Graph(
            id='grafico-etl-real',
            figure=px.bar(
                df_transformado.head(15), 
                x='SalesOrderID',
                y='LineTotal_Calculated',
                title='Faturamento por ID de Pedido (Dados Transformados via Python)',
                template='plotly_white',
                labels={'SalesOrderID': 'ID do Pedido', 'LineTotal_Calculated': 'Faturamento Calculado ($)'}
            )
        )
    ])

    if __name__ == '__main__':
        app.run(jupyter_mode='inline', port=8050)

=== [ETL] 1. EXTRAÇÃO REAL CONCLUÍDA: 121316 registros carregados ===

KeyError: 'OrderQty'

In [5]:
import pandas as pd

# 1. Caminho real do seu arquivo CSV
caminho_arquivo = 'C:/Users/mdiir/Documents/code_unisales/Database_Tunning/AdventureWorks-for-Postgres-master/SalesOrderDetail.csv'

# 2. Lendo o arquivo
df_real = pd.read_csv(caminho_arquivo, sep=',')

print("=== COLUNAS EXISTENTES NO SEU ARQUIVO CSV ===")
print(df_real.columns.tolist())

=== COLUNAS EXISTENTES NO SEU ARQUIVO CSV ===
['43659\t1\t4911-403C-98\t1\t776\t1\t2024.9940\t.0000\t2024.994000\tB207C96D-D9E6-402B-8470-2CC176C42283\t2022-05-30 00:00:00.000']

In [7]:
import pandas as pd

# 1. Caminho real do arquivo CSV do AdventureWorks na sua máquina
caminho_arquivo = 'C:/Users/mdiir/Documents/code_unisales/Database_Tunning/AdventureWorks-for-Postgres-master/SalesOrderDetail.csv'

# 2. Definindo os nomes reais das colunas da tabela SalesOrderDetail do AdventureWorks
colunas_sales_order_detail = [
    'SalesOrderID', 'SalesOrderDetailID', 'CarrierTrackingNumber', 
    'OrderQty', 'ProductID', 'SpecialOfferID', 'UnitPrice', 
    'UnitPriceDiscount', 'LineTotal', 'rowguid', 'ModifiedDate'
]

# 3. EXTRAÇÃO (Extract) em memória usando Pandas (separador por tabulação '\t', sem cabeçalho original)
print("=== ETAPA 1: EXTRAÇÃO EM MEMÓRIA ===")
df_real = pd.read_csv(caminho_arquivo, sep='\t', header=None, names=colunas_sales_order_detail)
print(f"Total de registros carregados na RAM: {len(df_real)}")

# 4. TRANSFORMAÇÃO (Transform) em memória
print("\n=== ETAPA 2: TRANSFORMAÇÃO EM MEMÓRIA ===")
# Removendo duplicatas, se houver
df_transformado = df_real.drop_duplicates().copy()

# Tratamento de valores nulos nas colunas numéricas
df_transformado['OrderQty'] = df_transformado['OrderQty'].fillna(0)
df_transformado['UnitPrice'] = df_transformado['UnitPrice'].fillna(0.0)

# Criando métrica derivada em memória (Regra de Negócio: Faturamento Total da Linha com Desconto)
df_transformado['LineTotal_Calculated'] = (
    df_transformado['OrderQty'] * df_transformado['UnitPrice']
) * (1 - df_transformado['UnitPriceDiscount'])

print(f"Total de registros após limpeza e transformação: {len(df_transformado)}")

# 5. Exibindo uma amostra dos dados processados em memória
print("\n=== AMOSTRA DOS DADOS PROCESSADOS (HEAD) ===")
display(df_transformado[['SalesOrderID', 'OrderQty', 'UnitPrice', 'UnitPriceDiscount', 'LineTotal_Calculated']].head(10))

# 6. Agregação analítica simples em memória (exemplo de KPI: Faturamento Total por Pedido)
df_resumo_pedido = df_transformado.groupby('SalesOrderID')['LineTotal_Calculated'].sum().reset_index()
df_resumo_pedido.rename(columns={'LineTotal_Calculated': 'TotalFaturamento'}, inplace=True)

print("\n=== RESUMO ANALÍTICO EM MEMÓRIA (TOP 5 PEDIDOS) ===")
display(df_resumo_pedido.sort_values(by='TotalFaturamento', ascending=False).head(5))

=== ETAPA 1: EXTRAÇÃO EM MEMÓRIA ===
Total de registros carregados na RAM: 121317

=== ETAPA 2: TRANSFORMAÇÃO EM MEMÓRIA ===
Total de registros após limpeza e transformação: 121317

=== AMOSTRA DOS DADOS PROCESSADOS (HEAD) ===

   SalesOrderID  OrderQty  UnitPrice  UnitPriceDiscount  LineTotal_Calculated
0         43659         1  2024.9940                0.0             2024.9940
1         43659         3  2024.9940                0.0             6074.9820
2         43659         1  2024.9940                0.0             2024.9940
3         43659         1  2039.9940                0.0             2039.9940
4         43659         1  2039.9940                0.0             2039.9940
5         43659         2  2039.9940                0.0             4079.9880
6         43659         1  2039.9940                0.0             2039.9940
7         43659         3    28.8404                0.0               86.5212
8         43659         1    28.8404                0.0               28.8404
9         43659         6     5.7000                0.0               34.2000

=== RESUMO ANALÍTICO EM MEMÓRIA (TOP 5 PEDIDOS) ===

C:\Users\mdiir\AppData\Local\Temp\ipykernel_17876\223205877.py:40: Pandas4Warning: The inplace keyword in DataFrame.rename is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df_resumo_pedido.rename(columns={'LineTotal_Calculated': 'TotalFaturamento'}, inplace=True)

       SalesOrderID  TotalFaturamento
7472          51131     163930.394292
11623         55282     160378.391334
2957          46616     150837.438737
3322          46981     147390.932828
3736          47395     146154.565252